### ISSUE TITLE
How to access a reducer of same logic into other logic.

### ISSUE THREAD

**Issue by arunfancraze** [keajs/kea#156]
Let us say I have following code

```javascript
reducers(({ props }) => ({
        filters: [
            props.propertyFilters ? parseProperties(props.propertyFilters) : ([] as AnyPropertyFilter[]),
            {
                setFilter: (state, { index, property }) => {
                    const newFilters: AnyPropertyFilter[] = [...state]
                    newFilters[index] = property
                    return newFilters
                },
            },
        ],
        filtersOperatorsCache: [
            props.propertyFilters
                ? parsePropertiesForFiltersCache(props.propertyFilters)
                : ([] as FilterOperatorCache[]),
            {
                setFilterCaches: (state, { index, operator, property }) => {
                    const newFiltersCache: FilterOperatorCache[] = [...state]
                    newFiltersCache[index] = { ...newFiltersCache[index], [operator]: property }
                    return newFiltersCache
                },
            },
        ],
    })),
``` 

I want to access `filtersOperatorsCache` inside `setFilter` of `filters` reducer. How to do that.

**Comment by arunfancraze** [comment]
Sorry, I got it

**Comment by arunfancraze** [comment]
I tried using `reducers(({ values, props }) => ({` but I am getting an error 
```javascript
Uncaught Error: You may not call store.getState() while the reducer is executing. The reducer has already received the state as an argument. Pass it down from the top reducer instead of reading it from the store.
    at Object.getState (redux.js:196:13)
    at Object.a [as getState] (<anonymous>:1:38452)
    at getStoreState2 (index.cjs.js:1013:29)
    at Object.get [as filtersOperatorsCache] (index.cjs.js:1744:37)
    at Object.setFilter [as set filter (lib.components.PropertyFilters.propertyFilterLogic.0-$pageview-trends_TRENDS_data_exploration-filter)] (propertyFilterLogic.ts:54:40)
```

**Comment by mariusandra** [comment]
You can't access other values inside a reducer. You can either have these values as part of a reducer, or use a listener for more complex logic flow.

**Comment by arunfancraze** [comment]
Got it @mariusandra
