### ISSUE TITLE
Testing does not seem to be documented properly

### ISSUE THREAD

**Issue by alp82** [keajs/kea#63]
I am trying to find real-life examples for working tests because the documentation for [Testing](https://kea.js.org/guide/testing) is not working for me.

My app was initially generated by create-react-app.

Here is my test file:
```
import React from 'react';
import ReactDOM from 'react-dom';
import { createStore, applyMiddleware, combineReducers, compose } from 'redux';
import createSagaMiddleware from 'redux-saga';
import { resetKeaCache, keaReducer } from 'kea';
import keaSaga from 'kea-saga';

beforeEach(() => {
  resetKeaCache();
});

const getStore = () => {
  const reducers = combineReducers({
    scenes: keaReducer('scenes'),
  });

  const sagaMiddleware = createSagaMiddleware();
  const finalCreateStore = compose(applyMiddleware(sagaMiddleware))(createStore);

  const store = finalCreateStore(reducers);

  sagaMiddleware.run(keaSaga);

  return store;
};

it('renders without crashing', () => {
  const store = getStore();
  const App = require('./App').default;

  const div = document.createElement('div');
  ReactDOM.render(App, div);
});
```

And this is App.js
```
import React from 'react';
import { Switch, Route } from 'react-router-dom';

import Sidebar from './main/Sidebar';
import CounterTest from './CounterTest';

const App = () => (
  <div className="content-fluid">
    <main>
      <Switch>
        <Route exact path="/" component={CounterTest} />
      </Switch>
    </main>
  </div>
);

export default App;
```

Here is CounterTest.js
```
import React from 'react';
import PropTypes from 'prop-types';
import { delay } from 'redux-saga';
import { kea } from 'kea';

const logic = kea({
  actions: () => ({
    increment: amount => ({ amount }),
    decrement: amount => ({ amount }),
  }),

  reducers: ({ actions }) => ({
    counter: [
      0,
      PropTypes.number,
      {
        [actions.increment]: (state, payload) => state + payload.amount,
        [actions.decrement]: (state, payload) => state - payload.amount,
      },
    ],
  }),

  selectors: ({ selectors }) => ({
    doubleCounter: [() => [selectors.counter], counter => counter * 2, PropTypes.number],
  }),

  takeLatest: ({ actions, workers }) => ({
    [actions.increment]: workers.sendToFakeServer,
    [actions.decrement]: workers.sendToFakeServer,
  }),

  workers: {
    *sendToFakeServer(action) {
      const { type } = action;
      const { amount } = action.payload;

      console.log(`${type} action called with amount '${amount}'`);
      yield delay(500);
      console.log('fake server responsed with yay!');
    },
  },
});

const CounterTest = ({ counter, doubleCounter, actions }) => {
  const { increment, decrement } = actions;

  return (
    <div className="container">
      Count: {counter}
      <br />
      Doublecount: {doubleCounter}
      <br />
      <button className="btn" onClick={() => increment(1)}>
        Increment
      </button>
      <button className="btn" onClick={() => decrement(1)}>
        Decrement
      </button>
    </div>
  );
};

CounterTest.propTypes = {
  actions: PropTypes.shape({
    increment: PropTypes.func.isRequired,
    decrement: PropTypes.func.isRequired,
  }).isRequired,
  counter: PropTypes.number.isRequired,
  doubleCounter: PropTypes.number.isRequired,
};

export default logic(CounterTest);
```

Errors i get:
```
  ● Console

    console.error node_modules\fbjs\lib\warning.js:33
      Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/react-polyfills
    console.error node_modules\redux-saga\lib\internal\utils.js:240
      uncaught at check runSaga(storeInterface, saga, ...args): saga argument must be a Generator function!

  ● renders without crashing

    runSaga(storeInterface, saga, ...args): saga argument must be a Generator function!

      at check (node_modules/redux-saga/lib/internal/utils.js:45:11)
      at runSaga (node_modules/redux-saga/lib/internal/runSaga.js:31:22)
      at getStore (src/App.test.js:22:18)
      at Object.<anonymous>.it (src/App.test.js:28:17)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

Sometimes also:
```
  ● Test suite failed to run

    TypeError: Cannot read property 'render' of undefined

      at isStateless (node_modules/kea/lib/kea/index.js:42:31)
      at response (node_modules/kea/lib/kea/index.js:227:10)
      at Object.<anonymous> (src/demo/CounterTest.js:72:1)
      at Object.<anonymous> (src/demo/CounterFlowTest.test.js:3:20)
          at <anonymous>

```

Btw: "NOTE! This section of the guide is still heavily under construction! Please check back in a few days." seems to be on that site for at least two months.

**Comment by dlasky** [comment]
i had a similar issue and doing the 'manual setup' instead of using getStore fixed it for me:

```
import { createStore, applyMiddleware, combineReducers, compose } from 'redux'
import { keaReducer } from 'kea'

const reducers = combineReducers({
  kea: keaReducer('kea'),
  scenes: keaReducer('scenes')
  // other app reducers here
})

const finalCreateStore = compose(
  // middlewares here
)(createStore)

const store = finalCreateStore(reducers)
```

**Comment by duanecilliers** [comment]
I've [submitted a PR](https://github.com/keajs/kea-website/pull/9) that solved the issue for me. The default export in [kea-saga](https://github.com/keajs/kea-saga) is `sagaPlugin` Try changing 
`import keaSaga from 'kea-saga';`
to 
` import { keaSaga } from 'kea-saga';`
